install: pkg-config --list-all && sudo apt-get -y -q install build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libgtkmm-2.4-dev libglew-dev libopencv-dev && wget https://launchpad.net/~dns/+archive/gnu/+build/3647209/+files/autoconf_2.69-1gnu1~12.04_all.deb && sudo dpkg -i autoconf_2.69-1gnu1~12.04_all.deb && sudo echo -e "deb http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main\ndeb-src http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main" | sudo tee /etc/apt/sources.list && sudo apt-get update && sudo apt-get -q -y install boost1.55
script: autoreconf && ./configure && make check
language: cpp
compiler:
  - gcc

